Repository CoPlay-FE/coplan, pull requests merged in 2025-06, with the labels that each got.

#12 🐛 fix: GitHub Actions 배포 스크립트 Docker 서비스명 수정
  .github/workflows/deploy.yml
Labels: 🐛Fix

#13 🐛 fix: Docker 빌드 에러 해결 및 배포 스크립트 권한 문제 수정
  Dockerfile
Labels: 🐛Fix

#16 🐛 fix: 메모리 부족으로 인한 배포 실패 문제
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
Labels: 🐛Fix

#17 🐛 fix: Next.js 14 표준 standalone 배포 방식 적용
  Dockerfile
  next.config.mjs
Labels: 🐛Fix

#19 🐛 fix: 기존의 t2.micro 메모리 부족 문제 해결을 위한 standalone 및 기존 설정 제거
  .github/workflows/deploy.yml
  Dockerfile
Labels: 🐛Fix, 🚀 Deploy

#23 🐛 fix: 기존의 배포 실패 문제 해결 및 CD 파이프라인
  .github/workflows/deploy.yml
Labels: 🐛Fix, 🚀 Deploy

#33 ✨Feat: 공통 사용자 프로필 구현
  src/app/globals.css
  src/app/shared/components/common/Profile.tsx
  src/app/shared/components/common/header/Header.tsx
  src/app/shared/lib/cn.ts
  tsconfig.json
Labels: ✨Feat, 🎨Style

#43 ✨Feat: 공통 드롭다운 메뉴 기능 구현
  public/favicon.ico
  public/favicon.png
  src/app/globals.css
  src/app/layout.tsx
  src/app/shared/components/common/Dropdown/Dropdown.tsx
  src/app/shared/components/common/Profile.tsx
  src/app/shared/components/common/header/Header.tsx
  src/app/shared/components/common/header/UserDropdown.tsx
Labels: ✨Feat, 🐛Fix, 💄Modify

#48 ✨ Feat: 대시보드 상세 페이지 - 드래그 앤 드롭
  src/app/dashboard/[id]/Card/Card.tsx
  src/app/dashboard/[id]/Column/Column.tsx
  src/app/dashboard/[id]/api/updateCardColumn.ts
  src/app/dashboard/[id]/api/useCardMutation.ts
  src/app/dashboard/[id]/page.tsx
  src/app/dashboard/[id]/store/useDragStore.ts
Labels: ✨Feat

#51 ✨Feat: 공동 사용자 프로필 구현
  src/app/dashboard/[id]/edit/layout.tsx
  src/app/shared/components/common/Avatar.tsx
  src/app/shared/components/common/CollaboratorItem.tsx
  src/app/shared/components/common/Dropdown/Dropdown.tsx
  src/app/shared/components/common/Profile.tsx
  src/app/shared/components/common/UserInfo.tsx
  src/app/shared/components/common/header/Collaborator/CollaboratorList.tsx
  src/app/shared/components/common/header/Collaborator/Tooltip.tsx
  src/app/shared/components/common/header/Header.tsx
  src/app/shared/components/common/header/UserDropdown.tsx
  src/app/tester/page.tsx
Labels: ✨Feat, 🐛Fix, 🎨Style, 💄Modify, 📁Chore

#55 ✨ Feat: 대시보드 상세 페이지 - 터치 기반 드래그 앤 드롭
  src/app/dashboard/[id]/Card/Card.tsx
  src/app/dashboard/[id]/Card/Tags.tsx
  src/app/dashboard/[id]/Column/Column.tsx
  src/app/dashboard/[id]/api/useCardMutation.ts
  src/app/dashboard/[id]/page.tsx
  src/app/dashboard/[id]/store/useDragStore.ts
  src/app/dashboard/[id]/type/Card.ts
  src/app/globals.css
  src/app/shared/components/common/Avatar.tsx
  src/app/shared/lib/getColor.ts
  tailwind.config.ts
Labels: ✨Feat, 🎨Style, 🔧Chore

#69 ✨Feat: 회원가입 페이지 구현
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/features/auth/components/LoginForm.tsx
  src/app/features/auth/components/SignupForm.tsx
  src/app/features/auth/hooks/useAuth.ts
  src/app/features/auth/hooks/useSignupMutation.ts
  src/app/features/auth/hooks/useSignupSubmit.ts
  src/app/globals.css
  src/app/shared/hooks/useMounted.ts
  src/app/shared/types/user.type.ts
Labels: ✨Feat, 🎨Style, ♻️Refactor

#78 ✨Feat: 프로필 수정 컴포넌트 구현
  src/app/features/auth/api/authApi.ts
  src/app/features/auth/hooks/useLoginMutation.ts
  src/app/features/auth/hooks/useSignupMutation.ts
  src/app/features/mypage/api/mypageApi.ts
  src/app/features/mypage/api/mypageEndPoint.ts
  src/app/features/mypage/components/ProfileEditForm.tsx
  src/app/features/mypage/components/ProfileImageUpload.tsx
  src/app/features/mypage/hook/useUpdateMyProfileMutation.ts
  src/app/features/mypage/hook/useUploadProfileImageMutation.ts
  src/app/features/mypage/hook/useUserQurey.ts
  src/app/features/mypage/schemas/mypageValidation.ts
  src/app/features/mypage/types/mypage.type.ts
  src/app/globals.css
  src/app/mypage/page.tsx
  src/app/shared/components/Input.tsx
  src/app/shared/components/common/CloseCircleIcon/CloseCircleIcon.tsx
  src/app/shared/components/common/PlusIcon/PlusIcon.tsx
  src/app/shared/components/common/WhitePenIcon/WhitePenIcon.tsx
  src/app/shared/components/common/sidebar/modal/CreateDashboardModal.tsx
  src/app/shared/hooks/useDashboard.ts
  src/app/shared/lib/.gitkeep
  src/app/shared/lib/axios.ts
Labels: ✨Feat, 🐛Fix, 🎨Style

#85 ✨feat: 헤더 API 연동
  public/images/next-disabled.png
  public/images/next.png
  public/images/prev-disabled.png
  public/images/prev.png
  src/app/dashboard/[id]/edit/components/EditInfo.tsx
  src/app/dashboard/[id]/edit/components/EditInvitation.tsx
  src/app/dashboard/[id]/edit/components/EditMember.tsx
  src/app/dashboard/[id]/edit/layout.tsx
  src/app/dashboard/[id]/edit/page.tsx
  src/app/dashboard/[id]/layout.tsx
  src/app/features/auth/store/useAuthStore.ts
  src/app/features/dashboard/api/invitation.ts
  src/app/features/dashboard/components/edit/DeleteDashboardButton.tsx
  src/app/features/dashboard/components/edit/EditInfo.tsx
  src/app/features/dashboard/components/edit/EditInvitation.tsx
  src/app/features/dashboard/components/edit/EditMember.tsx
  src/app/features/dashboard/components/edit/mockMember.js
  src/app/layout.tsx
  src/app/shared/components/common/Avatar.tsx
  src/app/shared/components/common/Dropdown/Dropdown.tsx
  src/app/shared/components/common/GlobalModalRender.tsx
  src/app/shared/components/common/UserInfo.tsx
  src/app/shared/components/common/header/Header.tsx
  src/app/shared/components/common/header/LeftHeaderContent.tsx
  src/app/shared/components/common/header/NavItem.tsx
  src/app/shared/components/common/header/RightHeaderNav.tsx
  src/app/shared/components/common/header/UserDropdown.tsx
  src/app/shared/components/common/modal/CreateDashboardModal.tsx
  src/app/shared/components/common/modal/CreateInvitationModal.tsx
  src/app/shared/components/common/sidebar/Sidebar.tsx
  src/app/shared/hooks/useDashboard.ts
  src/app/shared/store/useModalStore.ts
  src/app/shared/store/useSelectedDashboardStore.ts
  src/app/shared/types/dashboard.ts
  src/app/shared/types/modal.ts
  src/app/tester/page.tsx
Labels: ✨Feat, 🎨Style, 💄Modify, 🔧Chore

#92 Feat: 리다이렉트 처리
  src/app/providers.tsx
  src/app/shared/components/Redirect.tsx
  src/app/shared/hooks/useFirstDashboardIdQuery.ts
Labels: ✨Feat

#93 🐛 fix: React key 중복 및 401 인증 오류 해결
  src/app/features/dashboard_Id/api/fetchCards.ts
  src/app/features/dashboard_Id/api/fetchColumns.ts
  src/app/mydashboard/components/MyDashboardGrid/MyDashboardGrid.tsx
  src/app/shared/components/common/sidebar/Sidebar.tsx
Labels: 🐛Fix

#98 ✨ feat: 컬럼 관리 기능 (생성/수정/삭제)
  src/app/dashboard/[id]/page.tsx
  src/app/features/dashboard_Id/Column/Column.tsx
  src/app/features/dashboard_Id/api/deleteColumn.ts
  src/app/features/dashboard_Id/api/fetchMembers.ts
  src/app/features/dashboard_Id/api/postCard.ts
  src/app/features/dashboard_Id/api/postCardImage.ts
  src/app/features/dashboard_Id/api/postColumn.ts
  src/app/features/dashboard_Id/api/putCard.ts
  src/app/features/dashboard_Id/api/updateCardColumn.ts
  src/app/features/dashboard_Id/api/updateColumn.ts
  src/app/features/dashboard_Id/components/ColumnModalRenderer.tsx
  src/app/features/dashboard_Id/components/CreateColumnModal.tsx
  src/app/features/dashboard_Id/components/DeleteColumnConfirmModal.tsx
  src/app/features/dashboard_Id/components/EditColumnModal.tsx
  src/app/features/dashboard_Id/hooks/useCreateColumn.ts
  src/app/features/dashboard_Id/hooks/useDeleteColumn.ts
  src/app/features/dashboard_Id/hooks/useUpdateColumn.ts
  src/app/features/dashboard_Id/store/useColumnModalStore.ts
  src/app/features/dashboard_Id/type/Column.type.ts
Labels: ✨Feat

#99 ✨ Feat: 카드 상세 모달 구현
  src/app/features/dashboard_Id/Card/Card.tsx
  src/app/features/dashboard_Id/Card/ColumnTitle.tsx
  src/app/features/dashboard_Id/Card/cardFormModals/CreateCardModal.tsx
  src/app/features/dashboard_Id/Card/cardFormModals/ModifyCardForm.tsx
  src/app/features/dashboard_Id/Card/cardModal/CardContent.tsx
  src/app/features/dashboard_Id/Card/cardModal/CardContentCopy.tsx
  src/app/features/dashboard_Id/Card/cardModal/CardModal.tsx
  src/app/features/dashboard_Id/Card/cardModal/Comment.tsx
  src/app/features/dashboard_Id/Card/cardModal/CommentForm.tsx
  src/app/features/dashboard_Id/Card/cardModal/CommentModifyForm.tsx
  src/app/features/dashboard_Id/Card/cardModal/Comments.tsx
  src/app/features/dashboard_Id/api/deleteCard.ts
  src/app/features/dashboard_Id/api/deleteComment.ts
  src/app/features/dashboard_Id/api/fetchComments.ts
  src/app/features/dashboard_Id/api/postComment.ts
  src/app/features/dashboard_Id/api/putCard.ts
  src/app/features/dashboard_Id/api/putComment.ts
  src/app/features/dashboard_Id/api/useCommentsQuery.ts
  src/app/features/dashboard_Id/api/useDeleteCardMutation.ts
  src/app/features/dashboard_Id/api/useDeleteCommentMutation.ts
  src/app/features/dashboard_Id/api/usePostCard.ts
  src/app/features/dashboard_Id/api/usePostCommentMutation.ts
  src/app/features/dashboard_Id/api/usePutCardMutation.ts
  src/app/features/dashboard_Id/api/usePutCommentsMutation.ts
  src/app/features/dashboard_Id/api/useUploadCardImage.ts
  src/app/features/dashboard_Id/hooks/useInfiniteScroll.ts
  src/app/features/dashboard_Id/type/ApiResponse.ts
  src/app/features/dashboard_Id/type/Comment.type.ts
  src/app/features/dashboard_Id/type/CommentFormData.type.ts
  src/app/globals.css
  src/app/shared/components/common/Avatar.tsx
  src/app/shared/hooks/useIsmobile.ts
  src/app/shared/hooks/useLockBodyScroll.ts
Labels: ✨Feat

#100 ✨feat: 대시보드 수정 페이지 API 연동
  public/images/management.png
  src/app/dashboard/[id]/edit/page.tsx
  src/app/features/dashboard/components/edit/DeleteDashboardButton.tsx
  src/app/features/dashboard/components/edit/EditInfo.tsx
  src/app/features/dashboard/components/edit/EditInvitation.tsx
  src/app/features/dashboard/components/edit/EditMember.tsx
  src/app/features/dashboard/components/edit/PaginationHeader.tsx
  src/app/features/dashboard/components/edit/mockMember.js
  src/app/shared/components/common/Avatar.tsx
  src/app/shared/components/common/CollaboratorItem.tsx
  src/app/shared/components/common/UserInfo.tsx
  src/app/shared/components/common/header/Collaborator/CollaboratorList.tsx
  src/app/shared/components/common/header/NavItem.tsx
  src/app/shared/components/common/header/RightHeaderNav.tsx
  src/app/shared/components/common/header/UserDropdown.tsx
  src/app/shared/components/common/modal/CreateDashboardModal.tsx
  src/app/shared/components/common/modal/CreateInvitationModal.tsx
  src/app/shared/components/dashboard/DashboardForm.tsx
  src/app/shared/hooks/useDashboard.ts
  src/app/shared/hooks/useDashboardForm.ts
  src/app/shared/hooks/useMembers.ts
  src/app/shared/hooks/usePagination.ts
  src/app/shared/lib/getTeamId.ts
  src/app/shared/store/useModalStore.ts
Labels: ✨Feat, 🐛Fix, 💄Modify

#104 ♻️refactor: 반응형 및 마무리 수정 작업
  src/app/dashboard/[id]/edit/page.tsx
  src/app/features/auth/hooks/useAuth.ts
  src/app/features/dashboard/components/edit/DeleteDashboardButton.tsx
  src/app/features/dashboard/components/edit/EditInfo.tsx
  src/app/features/dashboard/components/edit/EditInvitation.tsx
  src/app/features/dashboard/components/edit/EditMember.tsx
  src/app/features/dashboard/components/edit/PaginationHeader.tsx
  src/app/features/mypage/components/ProfileEditForm.tsx
  src/app/mypage/page.tsx
  src/app/shared/components/common/UserInfo.tsx
  src/app/shared/components/common/header/Collaborator/CollaboratorList.tsx
  src/app/shared/components/common/header/Header.tsx
  src/app/shared/components/common/header/LeftHeaderContent.tsx
Labels: 🎨Style, ♻️Refactor

#102 ♻️ refactor: 사이드바 무한스크롤 및 반응형
  src/app/features/dashboard_Id/components/EditColumnModal.tsx
  src/app/mydashboard/components/InvitedDashboardTable/InvitedDashboardRow.tsx
  src/app/mydashboard/components/InvitedDashboardTable/InvitedDashboardTable.tsx
  src/app/mydashboard/components/InvitedDashboardTable/SearchInput.tsx
  src/app/mydashboard/components/MyDashboardGrid/AddDashboardCard.tsx
  src/app/mydashboard/components/MyDashboardGrid/MyDashboardCard.tsx
  src/app/mydashboard/components/MyDashboardGrid/MyDashboardGrid.tsx
  src/app/mydashboard/page.tsx
  src/app/shared/components/common/modal/CreateDashboardModal.tsx
  src/app/shared/components/common/sidebar/DashboardItem.tsx
  src/app/shared/components/common/sidebar/Sidebar.tsx
  src/app/shared/hooks/useContainerInfiniteScroll.ts
  src/app/shared/hooks/useDashboardInfinite.ts
Labels: ✨Feat, 🐛Fix, 🎨Style, ♻️Refactor

#110 ♻️ refactor: CI/CD 파이프라인 메모리 최적화
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
Labels: ♻️Refactor

#112 ♻️ refactor: Dockerfile에 빌드 시점 환경변수 설정 추가
  Dockerfile
Labels: ♻️Refactor, 🚀 Deploy

#113 🎨 style: 사이드바 z-index 추가
  src/app/shared/components/common/sidebar/Sidebar.tsx
Labels: 🎨Style

#114 🔧 chore: 브랜치 트리거 설정 추가
  .github/workflows/deploy.yml
Labels: 🔧Chore

#117 ♻️Refactor: 헤더 및 대시보드 수정 페이지 리팩토링
  src/app/dashboard/[id]/edit/page.tsx
  src/app/dashboard/[id]/layout.tsx
  src/app/features/dashboard/components/edit/DeleteDashboardButton.tsx
  src/app/features/dashboard/components/edit/EditInvitation.tsx
  src/app/features/dashboard/components/edit/EditMember.tsx
  src/app/features/dashboard/components/edit/PaginationHeader.tsx
  src/app/shared/components/common/Dropdown/Dropdown.tsx
  src/app/shared/components/common/UserInfo.tsx
  src/app/shared/components/common/header/Collaborator/CollaboratorList.tsx
  src/app/shared/components/common/header/LeftHeaderContent.tsx
  src/app/shared/components/common/header/RightHeaderNav.tsx
  src/app/shared/hooks/useMembers.ts
  tailwind.config.ts
Labels: 🎨Style, 💄Modify, ♻️Refactor

#120 ♻️ refactor: 반응형 레이아웃 일관성 개선(브레이크포인트 추가)
  src/app/mydashboard/components/InvitedDashboardTable/InvitedDashboardRow.tsx
  src/app/mydashboard/components/InvitedDashboardTable/InvitedDashboardTable.tsx
  src/app/mydashboard/components/InvitedDashboardTable/SearchInput.tsx
  src/app/mydashboard/components/MyDashboardGrid/AddDashboardCard.tsx
  src/app/mydashboard/components/MyDashboardGrid/MyDashboardCard.tsx
  src/app/mydashboard/components/MyDashboardGrid/MyDashboardGrid.tsx
  src/app/mydashboard/page.tsx
  src/app/shared/components/common/sidebar/DashboardItem.tsx
  src/app/shared/components/common/sidebar/Sidebar.tsx
Labels: ♻️Refactor
